sudo: required
services:
    - docker

before_install:
    - docker build -t jialiw/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true jialiw/docker-react-test npm run test -- --coverage